name: Generate links for folders in README
on: [push]

jobs:
  generate_links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get links for folders
      run: |
        echo -n "" > README.md
        echo "Repository Structure" >> README.md
        const fs = require('fs');
        const path = require('path');
        let root = './Assets';
        let result = '';
        function walk(dir, level) {
            let files = fs.readdirSync(dir);
            files.forEach(file => {
                let stats = fs.statSync(path.join(dir, file));
                if (stats.isDirectory()) {
                    result += `${"  ".repeat(level)}|-- [${file}](https://github.com/$GITHUB_REPOSITORY/tree/main/${path.join(dir, file)})`;
                    walk(path.join(dir, file), level + 1);
                }
            });
        }
        walk(root, 1);
        fs.appendFileSync('README.md', result);
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README with links for folders"
        git push
        
