name: Generate links for folders in README
on: [push]

jobs:
  generate_links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get links for folders
      run: |
        git ls-tree --name-only -r --full-tree HEAD | grep -v '.git' > links.txt
        echo -n "" > README.md
        echo "Repository Structure" >> README.md
        while read -r line; do
          if [ -d "$line" ]
          then
            # Get indentation level
            level=$(echo $line | awk -F'/' '{print NF-1}')
            # Add indentation
            indent=""
            for ((i=0; i<$level; i++)); do
              indent="$indent  "
            done
            # Add line to README
            echo "$indent|-- [$(basename $line)](https://github.com/$GITHUB_REPOSITORY/tree/main/$line)" >> README.md
          fi
        done < links.txt
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[
