name: Generate links for folders in README
on: [push]

jobs:
  generate_links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get links for folders
      run: |
        find . -type d -path "*/Assets/*" -print > links.txt
        echo -n "" > README.md
        echo "Assets" >> README.md
        while read -r line; do
          # Get indentation level
          level=$(echo $line | awk -F'/' '{print NF-2}')
          # Add indentation
          indent=""
          for ((i=0; i<$level; i++)); do
            indent="$indent  "
          done
          #Add line to README
          echo "$indent|-- $(basename $line)" >> README.md
        done < links.txt
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README with links for folders"
        git push
